import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/component/NavBar";
import { Footer } from "@/components/component/Footer";
import AuthProvider from "@/components/component/authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>

      <body className={inter.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
      </AuthProvider>
    </html>
  );
}
